import React, { Component } from 'react';

const About = (props) => {
    return (
        <div className='container'>
            <h1>About</h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.</p>

            <h2>What we do</h2>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero nulla, commodo at mattis nec, laoreet quis nisi. Maecenas ullamcorper ex nec massa cursus, eleifend imperdiet justo pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam varius commodo tortor non convallis. Morbi nisl urna, tincidunt commodo semper at, sagittis eget tortor. Fusce vehicula tristique ante. Aliquam convallis vel dui nec blandit. Aliquam erat volutpat. Aenean lobortis felis sed dapibus hendrerit. Vivamus egestas, lacus non auctor malesuada, urna nisl hendrerit velit, sed cursus nisl nibh vel purus. Duis elementum tincidunt metus id vestibulum. Nunc dui odio, elementum quis facilisis nec, ultricies et nulla.</p>
        </div>
    );
}

export default About;